### ISSUE TITLE
@may-bee: As I changed and reworked quite a bit you could give it a test from the latest master if possible.

### ISSUE THREAD

**Issue by seweryn684** [m-m-m/util#261]
@may-bee: As I changed and reworked quite a bit you could give it a test from the latest master if possible.

_Originally posted by @hohwille in https://github.com/m-m-m/util/issues/132#issuecomment-65894998_

**Comment by hohwille** [comment]
@seweryn684 what are you intending with this issue?
Are you testing a bot that is trying to create issues for potential tasks from comments?
I am slightly confused. Are you user of my library because I almost never received feedback and do not actively develop the net.sf.m-m-m stuff anymore and replaced it with io.github.m-m-m.
Hence, I would simply close this issue...

**Comment by jsoref** [comment]
Seems to be a spammer:
https://github.com/check-spelling/check-spelling/wiki/_history:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/2119212/214226012-0d31388b-25f2-444e-b4a4-5d9683e1d6f4.png">
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/2119212/214226069-47dac466-c64f-43e4-bae6-26db631ed1d3.png">

**Comment by hohwille** [comment]
thanks @jsoref
